// #ifndef AMREX_TIMER_H_
// #define AMREX_TIMER_H_

// #include <AMReX_Config.H>
// #include <AMReX_Utility.H>

// namespace amrex {

// class Timer {

// public:

//     Timer ();

//     void start ();

//     void stop ();

//     void reset ();

//     double time ();

//     // std::string name () { return m_name; }

// protected:

//     // std::string m_name;
//     bool m_started = false;
//     double m_timer_time = 0.0;
//     double m_start_time = 0.0;

// };

// // std::ostream& operator<< (std::ostream& os, Timer& timer);

// }

// #endif /* AMREX_TIMER_H_ */